# docker / podman
#alias docker='podman'

# git
alias ss='${HOME}/usr/bin/push'

# ssh
alias rp='ssh raspberry-pi'

# tree
alias t='tree -L 1'
alias tt='tree -L 2'
alias ttt='tree -L 3'
alias tttt='tree -L 4'
alias ttttt='tree -L 5'
alias T='tree'
